# Generated by Django 5.1.1 on 2024-09-22 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='users',
        ),
    ]
